### ISSUE TITLE
Treeshaking RoadMap

### ISSUE THREAD

**Issue by h-a-n-a** [rolldown-rs/rolldown#85]
## Basic
- [x] basic import and export https://github.com/rolldown-rs/rolldown/pull/67 https://github.com/rolldown-rs/rolldown/pull/65
- [ ] nested import star and re-export(should include its real statements, at this step, importStar object is created at any time) https://github.com/rolldown-rs/rolldown/issues/86
- [ ] import star with variable tree-shaking, which should create importStar object on-demand(only if the specifier itself is called, not the specifier's property)
- [ ] add more test cases and align to esbuild

## Advanced
TODO...
